name: whisper4dart
description: "A Dart wrapper for whisper.cpp"
version: 0.1.4
repository: https://github.com/KernelInterrupt/whisper4dart

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  ffi: ^2.1.0
  libmpv_dart: ^0.0.2
  path: ^1.9.0
  collection: ^1.15.0
  http: ^1.2.1
  archive: ^3.4.10
  package_config: ^2.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  ffigen: ^9.0.1
  json_serializable: ^6.9.0
  build_runner: ^2.4.6
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
